<script lang="ts">
	import Code from '@fuzdev/fuz_code/Code.svelte';
	import {resolve} from '$app/paths';
	import {tome_get_by_slug} from '@fuzdev/fuz_ui/tome.ts';
	import TomeContent from '@fuzdev/fuz_ui/TomeContent.svelte';
	import TomeSection from '@fuzdev/fuz_ui/TomeSection.svelte';
	import TomeSectionHeader from '@fuzdev/fuz_ui/TomeSectionHeader.svelte';
	import DeclarationLink from '@fuzdev/fuz_ui/DeclarationLink.svelte';
	import TomeLink from '@fuzdev/fuz_ui/TomeLink.svelte';

	const TOME_SLUG = 'introduction';
	const tome = tome_get_by_slug(TOME_SLUG);
</script>

<TomeContent {tome}>
	<section>
		<p>
			mdz is a strict markdown dialect built for streaming, Svelte authoring, docs websites, and
			untrusted content. The same grammar serves multiple use cases:
		</p>
		<ul>
			<li>streaming output from LLMs and other live sources</li>
			<li>
				authoring with Svelte components, with an optional build-time preprocessor that compiles
				static usage to plain Svelte markup
			</li>
			<li>
				rendering TSDoc/JSDoc comments on docs websites with domain-specific behavior like
				backticked identifiers linkifying to API docs
			</li>
			<li>dynamic content from untrusted users, with granular control over enabled behaviors</li>
		</ul>
		<p>
			mdz's predictable grammar means streaming never re-parses: LLM output renders incrementally,
			and the infrequent corrections -- like an unclosed <code>**</code> or a link resolving late --
			are bounded, explicit opcodes. The streaming design is derived from
			<a href="https://github.com/pngwn">@pngwn</a>'s ideas in this
			<a href="https://bsky.app/profile/pngwn.at/post/3mi527zntb22n">Bluesky thread</a>
			(<a href="https://pngwn.at/">pngwn.at</a>), and other parts of the mdz design are inspired by
			pngwn's <a href="https://mdsvex.pngwn.io/">MDsveX</a>.
		</p>
		<p>
			mdz takes after <a href="https://commonmark.org/">CommonMark</a> and
			<a href="https://github.github.com/gfm/">GFM</a>, diverging where their rules fight streaming
			or carry avoidable complexity and ambiguity.
		</p>
		<p>It ships:</p>
		<ul>
			<li>
				<DeclarationLink name="Mdz" /> and <DeclarationLink name="MdzStream" />: Svelte 5 components
				to render regular and streaming content
			</li>
			<li>
				<DeclarationLink name="MdzStreamParser" />: an incremental parser that emits append-only
				rendering opcodes as chunks arrive, never re-parsing
			</li>
			<li>
				<DeclarationLink name="mdz_parse" />: a synchronous parser producing an
				<DeclarationLink name="MdzNode" /> tree
			</li>
			<li>
				<DeclarationLink name="svelte_preprocess_mdz" />: a preprocessor that compiles static mdz
				content to plain Svelte markup at build time
			</li>
		</ul>
		<p>
			AI disclosure: almost everything here was generated by machine agents except for the designs
			and intros. mdz is the result of 5+ years of prototyping ideas.
		</p>
		<p>
			For more see the docs ahead and the <a href="https://github.com/fuzdev/mdz">repo</a>.
		</p>
		<aside>
			⚠️ This project is pre-stable: breaking changes are expected and some features (like
			attributes) are not yet implemented. Feedback is welcome!
		</aside>
	</section>

	<TomeSection>
		<TomeSectionHeader text="Principles" />
		<ul>
			<li>
				<strong>Streaming is a property of the grammar, not just the parser</strong> — every ambiguity
				resolves within a bounded hold or an explicit, local opcode; constructs that break this (setext
				headings, reference links, the loose/tight list distinction) are excluded rather than worked around.
			</li>
			<li>
				<strong>One syntax per feature</strong> — <code>**bold**</code>, <code>_italic_</code>,
				<code>~~strike~~</code>, no alternate spellings.
			</li>
			<li>
				<strong>Chunking doesn't change the result</strong> — the streamed tree matches the one-shot parse
				(documented adversarial cases aside), and the parser never re-parses.
			</li>
			<li>
				<strong>Predictable over permissive</strong> — false negatives over false positives:
				<code>__init__</code>, intraword underscores, and stray <code>*</code> stay literal.
			</li>
			<li>
				<strong>Structure is the parser's job; presentation is the renderer's</strong> — whitespace style,
				syntax highlighting, and rich components inject at the rendering seam.
			</li>
			<li>
				<strong>Nothing renders by default except mdz</strong> — HTML elements and Svelte components must
				be registered; unregistered tags render as visible placeholders.
			</li>
		</ul>
	</TomeSection>

	<TomeSection>
		<TomeSectionHeader text="Install" />
		<Code lang={null} content="npm i -D @fuzdev/mdz" />
		<p>
			Svelte, SvelteKit, and <code>@fuzdev/fuz_util</code> are peer dependencies (fuz_util is used only
			by the build-time preprocessor).
		</p>
	</TomeSection>

	<TomeSection>
		<TomeSectionHeader text="Usage" />
		<p>Render static content:</p>
		<Code lang="ts" content="import Mdz from '@fuzdev/mdz/Mdz.svelte';" />
		<Code content={`<Mdz content="Some **bold** and \`code\` and a [link](/docs)." />`} />
		<p>Parse to a node tree:</p>
		<Code
			lang="ts"
			content={`import {mdz_parse} from '@fuzdev/mdz/mdz.js';

const nodes = mdz_parse('# Heading\\n\\nSome **bold** text.');`}
		/>
		<p>
			The <TomeLink slug="usage" /> docs walk through the full dialect with interactive examples, and
			the <a href={resolve('/docs/usage/grammar')}>formal grammar</a> is the normative syntax reference.
		</p>
	</TomeSection>

	<TomeSection>
		<TomeSectionHeader text="Styling" />
		<p>
			mdz renders plain semantic HTML — headings, tables, lists, blockquotes, code — and adds no
			classes of its own, so style it with whatever CSS you already use.
		</p>
		<p>
			One integration caveat with <code>@fuzdev/fuz_css</code>: its Vite plugin tree-shakes base
			styles by statically scanning source for element names, but mdz emits table cells, headings,
			and opt-in HTML through dynamic <code>&lt;svelte:element&gt;</code> that static analysis can't
			see — so those base styles get stripped. Opt them back in with the plugin's
			<code>additional_elements</code> option (a list, or <code>'all'</code> for the full base
			reset). This rough edge in the fuz_css integration is expected to be revisited.
		</p>
		<Code lang="ts" content={`vite_plugin_fuz_css({additional_elements: 'all'})`} />
	</TomeSection>

	<TomeSection>
		<TomeSectionHeader text="Streaming" />
		<p>
			Feed chunks to <DeclarationLink name="MdzStreamParser" /> as they arrive (e.g. from an LLM) and
			render the emitted opcodes with <DeclarationLink name="MdzStream" /> — the final tree is identical
			to what <DeclarationLink name="mdz_parse" /> produces for the same input, regardless of chunking.
			See the <TomeLink slug="streaming" /> docs for the live demo, usage, and the opcode design.
		</p>
	</TomeSection>

	<TomeSection>
		<TomeSectionHeader text="Rendering seam" />
		<p>
			By default, inline <code>`code`</code> renders as plain <code>&lt;code&gt;</code> and fenced
			code blocks render as plain <code>&lt;pre&gt;&lt;code&gt;</code>. Inject richer renderers via
			<DeclarationLink name="MdzRoot" /> — the prop contracts match fuz_ui's
			<a href="https://ui.fuz.dev/docs/api/DocsLink.svelte#DocsLink"><code>DocsLink</code></a>
			(auto-linked API identifiers) and fuz_code's
			<a href="https://code.fuz.dev/docs/api/Code.svelte#Code"><code>Code</code></a> (syntax highlighting):
		</p>
		<Code
			lang="svelte"
			content={`<MdzRoot code={DocsLink} codeblock={Code}>
	<Mdz content={content} />
</MdzRoot>`}
		/>
	</TomeSection>

	<TomeSection>
		<TomeSectionHeader text="Preprocessor" />
		<p>
			<DeclarationLink name="svelte_preprocess_mdz" /> compiles static
			<code>&lt;Mdz content="…"&gt;</code> usages to pre-rendered markup at build time, eliminating
			runtime parsing for known-static content — see the <TomeLink slug="svelte_preprocess_mdz" /> docs
			for setup and options.
		</p>
	</TomeSection>
</TomeContent>
